version: "3"
services:
  web: 
    image: nginx
    build:
      context: ./
      dockerfile: ./docker/web/dockerfile
    ports:
      - 80:80
    depends_on:
      - app
  app:  
    restart: always
    build: 
      context: ./
      dockerfile: ./docker/app/dockerfile
    depends_on:
      - database
  database:
    image: postgres
    volumes:
      - .db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432
      
networks:
  default:
    external:
      name: network-gces