name: GCES CD

# on:
#   push:
#     branches:
#       - "master"

on:
  pull_request:
    branches: "master"

jobs:
  ci-script:
    uses: DanilloGS/GCES-Docker-Ruby/.github/workflows/gces.ci.yml@main
  docker:
    needs: ci-script
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: danillogs/gces-2022-2:latest
