name: GCES CD

on:
  push
  #   branches: [master]
  # pull_request:
  #   branches: "master"

defaults:
  run:
    working-directory: ./aplicacao

jobs:
  build:
    uses: DanilloGS/GCES-Docker-Ruby/.github/workflows/gces.ci.yml@master
  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login on Docker
        run: docker login --username=danillogs --password=${{ secrets.DOCKERHUB_TOKEN }}
