name: GCES CI
on: push

defaults:
  run: docker network create network-gces
  run:
    working-directory: ./aplicacao

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building app
        run: docker-compose up -d
